---
engines:
  duplication:
    enabled: true
    config:
      languages:
       javascript:
            mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
  csslint:
    enabled: true
exclude_paths:
- config/
- tests/
- vendor/