---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
       javascript:
            mass_threshold: 50
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js
  - "**.css
exclude_paths:
- config/
- tests/
- vendor/