---
engines:
  duplication:
    enabled: true
    config:
      languages:
       javascript:
            mass_threshold: 50
  csslint:
    enabled: true
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.js"
  - "**.css"  
exclude_paths:
- config/
- tests/
- vendor/